Add base template for the Docker/k8s workshops
pjlewisuk/k8s-sa-workshop-resources pull request #1
Opened 2020-03-30 08:41 UTC by carlosafonso

This PR adds the base CloudFormation template to be used in the Docker and Kubernetes workshops. The template provides a common working environment for all workshop users, which includes a VPC with a public subnet and an EC2 instance with Docker and Docker Compose already installed.

2020-04-01 16:12 UTC, pjlewisuk commented on docker-working-env-base.yaml
> +Mappings:
I think we should use the SSM lookup method here to keep the template short and prevent the need for regular updates. You can see an example (for Amazon Linux 1) here: https://github.com/awslabs/amazon-ecs-nodejs-microservices/pull/8/commits/01e2615f7cff972c96b23921fb7b3a878dbf42f5

2020-04-01 16:12 UTC, pjlewisuk commented on docker-working-env-base.yaml
> +      ImageId: !FindInMap [RegionToAmiId, !Ref "AWS::Region", AMI]
This will need to change to reference the SSM AMI resource

2020-04-01 16:13 UTC, pjlewisuk requested changes
Hi Carlos. I think we should use the SSM-lookup method (https://aws.amazon.com/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-systems-manager-parameter-store/) instead of AMI mappings. I've linked to an example PR from another repo for you to reference.

2020-04-02 12:45 UTC, carlosafonso commented
Got it! Working on it. Thanks.

2020-04-02 12:58 UTC, carlosafonso commented
Done, using param from SSM: `/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2`.

2020-04-02 13:56 UTC, pjlewisuk approved these changes
LGTM

2020-04-02 13:56 UTC, merged